### ISSUE TITLE
Docs: public storybook

### ISSUE THREAD

**Issue by regulyarniy** [devianllert/react-essential-tools#3]
Hello!
I like your project, good job! I think it would be great if it would have links to live examples in main readme and components readme to public deployed storybook.
It will be more representative and no need to clone and build locally to see what it could do.
I could help prepare PR for this(travis config, add links to all readme), already implemented deploy in my fork: https://regulyarniy.github.io/react-essential-tools/ 
All you need to do if you like the idea - wait for PR to review, configure token in travis and merge changes :)

**Comment by devianllert** [comment]
Hi!
Sounds great. I would be glad if you prepare all this stuff and send PR 😀
